name: lint

defaults:
  run:
    working-directory: editorextensions/UVexplorer-integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: install
        run: npm ci
      - name: install in Angular app
        working-directory: editorextensions/UVexplorer-integration/control-panel
        run: npm ci
      - name: ESLint
        run: npm run lint
      - name: Prettier
        run: npm run prettier
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply prettier formatting changes
          branch: ${{ github.head_ref }}
