name: lint

defaults:
  run:
    working-directory: editorextensions/UVexplorer-integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: install
        run: npm install
      - name: ESLint
        run: npm run lint
      - name: Prettier
        run: npm run prettier
